kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
  labels:
    password: passwordmysql
secretGenerator:
- name: mysql-pass
  literals:
  - password=passwordmysql
resources:
  - wp.yaml
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
